# Generated by Django 6.0.7 on 2026-08-07 15:42

import accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_sellerprofile'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'ordering': ['-created_at'], 'verbose_name': 'Account', 'verbose_name_plural': 'Accounts'},
        ),
        migrations.AlterModelOptions(
            name='address',
            options={'ordering': ['-created_at'], 'verbose_name': 'Address', 'verbose_name_plural': 'Addresses'},
        ),
        migrations.AlterModelOptions(
            name='sellerprofile',
            options={'ordering': ['-created_at'], 'verbose_name': 'Seller Profile', 'verbose_name_plural': 'Seller Profiles'},
        ),
        migrations.AlterField(
            model_name='account',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, validators=[accounts.validators.validate_date_of_birth]),
        ),
        migrations.AlterField(
            model_name='account',
            name='email',
            field=models.EmailField(max_length=254, unique=True, validators=[accounts.validators.validate_account_email]),
        ),
        migrations.AlterField(
            model_name='account',
            name='gender',
            field=models.CharField(blank=True, choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other')], db_index=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='is_verified',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='account',
            name='phone',
            field=models.CharField(max_length=15, unique=True, validators=[accounts.validators.validate_phone]),
        ),
        migrations.AlterField(
            model_name='account',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/', validators=[accounts.validators.validate_image]),
        ),
        migrations.AlterField(
            model_name='account',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('SELLER', 'Seller'), ('CUSTOMER', 'Customer')], db_index=True, default='CUSTOMER', max_length=10),
        ),
        migrations.AlterField(
            model_name='address',
            name='address_line1',
            field=models.CharField(max_length=255, validators=[accounts.validators.validate_address_text]),
        ),
        migrations.AlterField(
            model_name='address',
            name='address_line2',
            field=models.CharField(blank=True, max_length=255, null=True, validators=[accounts.validators.validate_address_text]),
        ),
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(max_length=100, validators=[accounts.validators.validate_location_name]),
        ),
        migrations.AlterField(
            model_name='address',
            name='country',
            field=models.CharField(max_length=100, validators=[accounts.validators.validate_location_name]),
        ),
        migrations.AlterField(
            model_name='address',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='district',
            field=models.CharField(max_length=100, validators=[accounts.validators.validate_location_name]),
        ),
        migrations.AlterField(
            model_name='address',
            name='full_name',
            field=models.CharField(max_length=100, validators=[accounts.validators.validate_name]),
        ),
        migrations.AlterField(
            model_name='address',
            name='is_default',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='address',
            name='landmark',
            field=models.CharField(blank=True, max_length=255, null=True, validators=[accounts.validators.validate_address_text]),
        ),
        migrations.AlterField(
            model_name='address',
            name='phone',
            field=models.CharField(max_length=15, validators=[accounts.validators.validate_phone]),
        ),
        migrations.AlterField(
            model_name='address',
            name='pincode',
            field=models.CharField(max_length=10, validators=[accounts.validators.validate_pincode]),
        ),
        migrations.AlterField(
            model_name='address',
            name='state',
            field=models.CharField(max_length=100, validators=[accounts.validators.validate_location_name]),
        ),
        migrations.AlterField(
            model_name='sellerprofile',
            name='bank_account_name',
            field=models.CharField(max_length=100, validators=[accounts.validators.validate_bank_account_name]),
        ),
        migrations.AlterField(
            model_name='sellerprofile',
            name='bank_account_number',
            field=models.CharField(max_length=30, validators=[accounts.validators.validate_bank_account_number]),
        ),
        migrations.AlterField(
            model_name='sellerprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='sellerprofile',
            name='gst_number',
            field=models.CharField(max_length=20, unique=True, validators=[accounts.validators.validate_gst_number]),
        ),
        migrations.AlterField(
            model_name='sellerprofile',
            name='ifsc_code',
            field=models.CharField(max_length=20, validators=[accounts.validators.validate_ifsc_code]),
        ),
        migrations.AlterField(
            model_name='sellerprofile',
            name='is_verified',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='sellerprofile',
            name='shop_description',
            field=models.TextField(blank=True, null=True, validators=[accounts.validators.validate_shop_description]),
        ),
        migrations.AlterField(
            model_name='sellerprofile',
            name='shop_logo',
            field=models.ImageField(blank=True, null=True, upload_to='shop_logos/', validators=[accounts.validators.validate_image]),
        ),
        migrations.AlterField(
            model_name='sellerprofile',
            name='shop_name',
            field=models.CharField(max_length=150, validators=[accounts.validators.validate_shop_name]),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['email'], name='accounts_ac_email_b00920_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['phone'], name='accounts_ac_phone_f1755d_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['role'], name='accounts_ac_role_22b49e_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['is_verified'], name='accounts_ac_is_veri_2a91e4_idx'),
        ),
        migrations.AddIndex(
            model_name='address',
            index=models.Index(fields=['account'], name='accounts_ad_account_9614cf_idx'),
        ),
        migrations.AddIndex(
            model_name='address',
            index=models.Index(fields=['city'], name='accounts_ad_city_a5f6ae_idx'),
        ),
        migrations.AddIndex(
            model_name='address',
            index=models.Index(fields=['state'], name='accounts_ad_state_9aaef2_idx'),
        ),
        migrations.AddIndex(
            model_name='address',
            index=models.Index(fields=['pincode'], name='accounts_ad_pincode_2308c3_idx'),
        ),
        migrations.AddIndex(
            model_name='address',
            index=models.Index(fields=['is_default'], name='accounts_ad_is_defa_6555f1_idx'),
        ),
        migrations.AddIndex(
            model_name='sellerprofile',
            index=models.Index(fields=['account'], name='accounts_se_account_1d4c67_idx'),
        ),
        migrations.AddIndex(
            model_name='sellerprofile',
            index=models.Index(fields=['shop_name'], name='accounts_se_shop_na_c6a1c6_idx'),
        ),
        migrations.AddIndex(
            model_name='sellerprofile',
            index=models.Index(fields=['gst_number'], name='accounts_se_gst_num_dd119b_idx'),
        ),
        migrations.AddIndex(
            model_name='sellerprofile',
            index=models.Index(fields=['is_verified'], name='accounts_se_is_veri_65dbac_idx'),
        ),
    ]
