# Generated by Django 6.0.7 on 2026-07-20 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_refund'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
