# Generated by Django 6.0.7 on 2026-08-07 20:04

import orders.models
import orders.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_delete_payment'),
        ('products', '0003_alter_product_options_alter_productattribute_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at'], 'verbose_name': 'Order', 'verbose_name_plural': 'Orders'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'ordering': ['id'], 'verbose_name': 'Order Item', 'verbose_name_plural': 'Order Items'},
        ),
        migrations.AlterModelOptions(
            name='orderstatushistory',
            options={'ordering': ['-created_at'], 'verbose_name': 'Order Status History', 'verbose_name_plural': 'Order Status Histories'},
        ),
        migrations.AlterModelOptions(
            name='refund',
            options={'ordering': ['-created_at'], 'verbose_name': 'Refund', 'verbose_name_plural': 'Refunds'},
        ),
        migrations.AlterModelOptions(
            name='returnrequest',
            options={'ordering': ['-requested_at'], 'verbose_name': 'Return Request', 'verbose_name_plural': 'Return Requests'},
        ),
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(max_length=30, unique=True, validators=[orders.models.validate_order_number]),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[orders.models.validate_amount]),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.PositiveIntegerField(validators=[orders.models.validate_quantity]),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='total_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[orders.models.validate_amount]),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[orders.models.validate_amount]),
        ),
        migrations.AlterField(
            model_name='orderstatushistory',
            name='remarks',
            field=models.CharField(blank=True, max_length=255, validators=[orders.models.validate_remarks]),
        ),
        migrations.AlterField(
            model_name='refund',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[orders.models.validate_amount]),
        ),
        migrations.AlterField(
            model_name='returnrequest',
            name='reason',
            field=models.TextField(validators=[orders.validators.validate_return_reason]),
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.UniqueConstraint(fields=('order', 'variant'), name='unique_order_variant'),
        ),
        migrations.AddConstraint(
            model_name='returnrequest',
            constraint=models.UniqueConstraint(fields=('order',), name='unique_return_request_per_order'),
        ),
    ]
