# Generated by Django 6.0.7 on 2026-08-07 18:51

import django.utils.timezone
import products.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created_at'], 'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AlterModelOptions(
            name='productattribute',
            options={'ordering': ['attribute_name'], 'verbose_name': 'Product Attribute', 'verbose_name_plural': 'Product Attributes'},
        ),
        migrations.AlterModelOptions(
            name='productimage',
            options={'ordering': ['created_at'], 'verbose_name': 'Product Image', 'verbose_name_plural': 'Product Images'},
        ),
        migrations.AlterModelOptions(
            name='productinventory',
            options={'ordering': ['variant'], 'verbose_name': 'Product Inventory', 'verbose_name_plural': 'Product Inventories'},
        ),
        migrations.AlterModelOptions(
            name='productvariant',
            options={'ordering': ['variant_name'], 'verbose_name': 'Product Variant', 'verbose_name_plural': 'Product Variants'},
        ),
        migrations.AddField(
            model_name='productattribute',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productvariant',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productvariant',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(validators=[products.validators.validate_product_description]),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[products.validators.validate_discount_price]),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=200, validators=[products.validators.validate_product_name]),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[products.validators.validate_price]),
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(max_length=50, unique=True, validators=[products.validators.validate_sku]),
        ),
        migrations.AlterField(
            model_name='product',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, validators=[products.validators.validate_product_weight]),
        ),
        migrations.AlterField(
            model_name='productattribute',
            name='attribute_name',
            field=models.CharField(max_length=100, validators=[products.validators.validate_attribute_name]),
        ),
        migrations.AlterField(
            model_name='productattribute',
            name='attribute_value',
            field=models.CharField(max_length=255, validators=[products.validators.validate_attribute_value]),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='alt_text',
            field=models.CharField(blank=True, max_length=255, validators=[products.validators.validate_alt_text]),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to='products/', validators=[products.validators.validate_product_image]),
        ),
        migrations.AlterField(
            model_name='productinventory',
            name='low_stock_threshold',
            field=models.PositiveIntegerField(default=5, validators=[products.validators.validate_low_stock_threshold]),
        ),
        migrations.AlterField(
            model_name='productinventory',
            name='reserved_quantity',
            field=models.PositiveIntegerField(default=0, validators=[products.validators.validate_reserved_quantity]),
        ),
        migrations.AlterField(
            model_name='productinventory',
            name='stock_quantity',
            field=models.PositiveIntegerField(default=0, validators=[products.validators.validate_stock_quantity]),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='discount_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[products.validators.validate_discount_price]),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[products.validators.validate_price]),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='sku',
            field=models.CharField(max_length=50, unique=True, validators=[products.validators.validate_sku]),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='variant_name',
            field=models.CharField(max_length=100, validators=[products.validators.validate_variant_name]),
        ),
        migrations.AddConstraint(
            model_name='productattribute',
            constraint=models.UniqueConstraint(fields=('product', 'attribute_name', 'attribute_value'), name='unique_product_attribute'),
        ),
        migrations.AddConstraint(
            model_name='productvariant',
            constraint=models.UniqueConstraint(fields=('product', 'variant_name'), name='unique_product_variant_name'),
        ),
    ]
