# Generated by Django 6.0.7 on 2026-08-09 11:41

import contact.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactmessage',
            options={'ordering': ('-created_at',), 'verbose_name': 'Contact Message', 'verbose_name_plural': 'Contact Messages'},
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='message',
            field=models.TextField(validators=[contact.validators.validate_message]),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='name',
            field=models.CharField(max_length=100, validators=[contact.validators.validate_name]),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='subject',
            field=models.CharField(max_length=255, validators=[contact.validators.validate_subject]),
        ),
    ]
