# Generated by Django 6.0.7 on 2026-08-09 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supportticket',
            options={'ordering': ('-created_at',), 'verbose_name': 'Support Ticket', 'verbose_name_plural': 'Support Tickets'},
        ),
        migrations.AlterModelOptions(
            name='ticketreply',
            options={'ordering': ('created_at',), 'verbose_name': 'Ticket Reply', 'verbose_name_plural': 'Ticket Replies'},
        ),
    ]
