# Generated by Django 6.0.7 on 2026-08-09 22:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_options_alter_productattribute_options_and_more'),
        ('wishlist', '0002_alter_wishlist_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wishlist',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveConstraint(
            model_name='wishlist',
            name='unique_account_product_wishlist',
        ),
        migrations.AddField(
            model_name='wishlist',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wishlist_variants', to='products.productvariant'),
        ),
        migrations.AddConstraint(
            model_name='wishlist',
            constraint=models.UniqueConstraint(fields=('account', 'product', 'variant'), name='unique_account_product_variant_wishlist'),
        ),
    ]
