# Generated by Django 6.0.7 on 2026-08-09 22:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_options_alter_productattribute_options_and_more'),
        ('wishlist', '0003_alter_wishlist_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wishlist_variants', to='products.productvariant'),
        ),
    ]
